### ISSUE TITLE
WMTS offset in V1.16 and not in V1.15.2

### ISSUE THREAD

**Issue by jcz7021** [Maproom/qmapshack#430]
### Describe the bug
[comment]: # (A clear and concise description of what the bug is)
An imagery offset is applied on V1.16.0 and that was not the case in V1.15.2 for a wmts map (see link below)

### What have you done to circle down the problem?
[comment]: # (Did you compare to previous versions? What versions? Did you check if others have the same problem?)
I've downgraded QMapShack to V1.15.2 and the bug is not present (see screenshots below)

### To Reproduce
[comment]: # (List the steps to reproduce the behavior)

1. Open a Gpx to have a reference point
2. Activate the specified wtms map on V1.15.2
3. Take a screenshot
4. Install V1.16.0
5. Open the same Gpx to have the same reference point
6. Activate the specified wtms map
7. Take a screenshot
6. Compare the screenshots : you can see the track having an offset

### Expected behavior
[comment]: # (A clear and concise description of what you expected to happen)
Track from Gpx should appear at the same position when comparing the two screenshots

### Screenshots
[comment]: # (If applicable, add screenshots to help explain your problem)
![1 15 2](https://user-images.githubusercontent.com/42817564/124672709-c925a100-deb7-11eb-9614-dd5d61ed6949.png)
![1 16 0](https://user-images.githubusercontent.com/42817564/124672722-ce82eb80-deb7-11eb-997b-37cf79c6232a.png)

### Attachments
[comment]: # (Can you provide an example file to trigger the problem?)

### Tracebacks
[comment]: # (Add your backtrace below if you have one. If QMapshack crashes the fastest way to get help is a backtrace.
For Linux see: https://github.com/Maproom/qmapshack/wiki/TroubleShooting#create-a-backtrace-of-a-crash-on-linux.
For Windows it would need a debug build and running QMapshack in Visual Studio.)

### Desktop
[comment]: # (please complete the following information)

 - OS: Windows 10 20H2
 - QMapShack Version:   1.16.0

### Additional context
[comment]: # (Add any other context about the problem here)

WMTS URL : https://geoservices.wallonie.be/arcgis/rest/services/IMAGERIE/ORTHO_LAST/MapServer/WMTS/1.0.0/WMTSCapabilities.xml

**Comment by wthaem** [comment]
Seems to be an old friend on Windows systems! Noticed and described several times earlier. Couldn't be reproduced systematically up to now.

**Comment by jcz7021** [comment]
Maybe it could be related to the EPSG:31370 used in this case ?
Seems more specific : https://epsg.io/31370

The other wmts map has no problem but she's using EPSG:3857.

**Comment by mitxel-m** [comment]
I'm afraid that this is not an issue related to windows version, because I can confirm this on Linux too.

I have composed a map view loading this WMTS with some transparency above the opentopomap layer, and here are the screenshots:

QMS 1.15.2 compiled against GDAL 3.0.4 + PROJ 7.0.0:


[](https://i.ibb.co/zRZ5v8S/QMS-1-15-proj7.jpg)

![](https://i.ibb.co/zRZ5v8S/QMS-1-15-proj7.jpg)

QMS 1.16.0 compiled against GDAL 3.0.4 + PROJ 8.0.0:

![](https://i.ibb.co/W24gyYD/QMS-1-16-proj8.jpg)


Then I have also checked what returns `projinfo` for EPSG:31370

`projinfo EPSG:31370 -o PROJ`

With proj 7.0.0 I get

`+proj=lcc +lat_0=90 +lon_0=4.36748666666667 +lat_1=51.1666672333333 +lat_2=49.8333339 +x_0=150000.013 +y_0=5400088.438 +ellps=intl +towgs84=-99.059,53.322,-112.486,0.419,-0.83,1.885,-1 +units=m +no_defs +type=crs`


With proj 8.0.0 I get

`+proj=lcc +lat_0=90 +lon_0=4.36748666666667 +lat_1=51.1666672333333 +lat_2=49.8333339 +x_0=150000.013 +y_0=5400088.438 +ellps=intl +units=m +no_defs +type=crs`

The outpout is different: 7.0.0 output includes a +towgs84= string that is missing in 8.0.0 output.


I wonder if the problem is that CMapWMTS.cpp wants to define the CRS for a WMTS with the  `exportToProj4` function, and now with PROJ 8 it doesn't get the expected string, as it happens with projinfo.

[see CMapWMTS.cpp line #221](https://github.com/Maproom/qmapshack/blob/5a1280938d9e81dc19853822dc0ecab3305fbaa2/src/qmapshack/map/CMapWMTS.cpp#L221)

Thre is a warning about the use of this function in GDAL documentation: 
[here](https://gdal.org/api/ogrspatialref.html#_CPPv4NK19OGRSpatialReference13exportToProj4EPPc) and [here](https://gdal.org/api/ogr_srs_api.html#_CPPv416OSRExportToProj420OGRSpatialReferenceHPPc)


May be this could affect not only WMTS maps but also VRTs. I have tried to reproduce it with some raster maps using the ED50 datum, but luckily they are well placed.





For reference. Other projects have also faced this problem. Here are some related articles:

https://cran.r-project.org/web/packages/rgdal/vignettes/CRS_projections_transformations.html#PR(phi)J

https://inbo.github.io/tutorials/tutorials/spatial_crs_coding/

HTH

**Comment by wthaem** [comment]
I can confirm the Mitxel's last phrase - me too, I had some strange (but not quite clear) behavior of the projection wizard. From time to time it requires to set up a projection, whereas a projection should already be known and not all epsg codes are accepted as input.

**Comment by mitxel-m** [comment]
I have been testing by replacing the exportToProj function by exportToWkt in CMapWMTS.cpp and it worked.

Here is a PR :https://github.com/Maproom/qmapshack/pull/446

But for get it working  you first have to get a Proj8 newer than 2021/09/26, which has already fixed the bug in PROJ8 reported by kiozen * *[reference here](https://github.com/OSGeo/PROJ/issues/2866)* if not you get the 'invalid latitude' error.

As I couldn't get the latest version of PROJ8 and compile it, I tried it after merging [this PR made by kiozen](https://github.com/Maproom/qmapshack/pull/442), which provides its own functions instead of the buggy PROJ ones.

I have also tested my PR with the current buggy version of PROJ8, and the rest of the WMTS maps I use are still working fine without changes. It would be good if someone else can test with other WMTS.

My coding skills are very limited, so this has to be taken with prudence, but I think that this could help to solve this issue.

Note: The same can be done  for https://github.com/Maproom/qmapshack/issues/438

**Comment by mitxel-m** [comment]
Solved with PR #447

**Comment by jcz7021** [comment]
Hi,
I've just tested the latest release V_1.16.1 (on windows 10) and imagery does not appears as you can see.
It seems that it is not resolved or, the bug is only available on windows 10.

![image](https://user-images.githubusercontent.com/42817564/149614977-e67e7445-5049-4ea3-9fb0-6cac7e6d084a.png)

**Comment by mitxel-m** [comment]
Next Wednesday I could take a look on windows 10.

@jcz7021   Can you provide your wmts file, so I could  do the test with the same source ?

**Comment by wthaem** [comment]
Attached snapshot shows an overlay of an openstreetmap map and the Wallonie map (centre of Namur). Can't see a problem with map display.

My environment: Windows10, QMS latest dev commit.

![capture_004_17012022_092559](https://user-images.githubusercontent.com/55309218/149734450-97e2ddf7-96a0-4bd5-a23b-6ff6511548d3.png)

![capture_002_17012022_092258](https://user-images.githubusercontent.com/55309218/149734474-1f52bdca-431b-40d0-9301-2b2dc2872df1.png)

**Comment by jcz7021** [comment]
@mitxel-m : the wmts is the one from my first post :

WMTS URL : https://geoservices.wallonie.be/arcgis/rest/services/IMAGERIE/ORTHO_LAST/MapServer/WMTS/1.0.0/WMTSCapabilities.xml

Tested with my business laptop today : was still in 1.15.2 so it is ok

![image](https://user-images.githubusercontent.com/42817564/149737931-fbe64558-909f-4cac-a084-2a831e4d3a6e.png)

Tested after upgrading to 1.16.1 : nothing is displayed

![image](https://user-images.githubusercontent.com/42817564/149738080-bff9c9df-3d6e-4064-a01f-d636aa353d53.png)

**Comment by mitxel-m** [comment]
I can confirm  the same, as @jcz7021,  with 1.16.1 from windows installer. (No tiles displayed)

The log file reports:
 `https://geoservices.wallonie.be/arcgis/rest/services/IMAGERIE/ORTHO_LAST/MapServer/WMTS/tile/1.0.0/IMAGERIE_ORTHO_LAST/default/default028mm/16/1222519/1044182.jpg - server replied: Introuvable"`


I have also noticed that the grid for EPSG:31370 is displayed with strange coordinates.

Remark that QMS 1.16.1 from windows installer comes with  proj 8.1.0, however, @wthaem has own compiled QMS with proj 8.2.0 which shows the tiles fine .

I am not absolutely sure but this seems to be related to a bug in proj 8.1.0 that returned an erroneous lat/lon. The bug was reported by kiozen, and is now fixed in Proj 8.2.0 (released november 1st). A similar case for a map not displaying was reported on the mailing list and finally resolved using proj 8.2.0.

I guess we'll have to wait for @huirad  or some other volunteer to kindly release a new installer including proj 8.2.0 or higher.

I think we should edit the wiki, and point out that proj 8.2.0 or higher is required.

**Comment by jcz7021** [comment]
Thanks for the confirmation !

I'll wait an updated windows installer to try again, no problem.

Thanks in advance to the volunteer :-)

**Comment by kiozen** [comment]
Can you please test this one:

https://magentacloud.de/s/Ry7jmqJoggcA3cT

**Comment by jcz7021** [comment]
@kiozen : yes it's working with this version as you can see 👍 

Great thanks !

REM : version is still 1.16.1 in the title bar but it's ok.

Thanks to all.

![image](https://user-images.githubusercontent.com/42817564/150507031-cf5d9927-9f9a-4bd5-8e3e-140e6122aba2.png)

**Comment by kiozen** [comment]
Keep in mind this is no bug in QMapShack but in Proj. This is just an updated of the binary in Windows. I uploaded the new binary.

**Comment by mitxel-m** [comment]
Tested and working for me too.
Thanks @kiozen
